apiVersion: v1
kind: Service
metadata:
  name: temporalite
spec:
  ports:
    - name: "7233"
      port: 7233
      targetPort: 7233
    - name: "8233"
      port: 8233
      targetPort: 8233
  selector:
    app: temporalite
  type: LoadBalancer
status:
  loadBalancer: {}